(package-initialize)
(require 'cl)
(setq custom-file "~/.emacs-custom.el")
(when (file-exists-p custom-file) (load custom-file))

(defun load.d (name)(load (concat "~/.emacs.d/" name ".el")))
(load.d "global-keys")
(load.d "packages")
(load.d "helm-conf")
(load.d "workspaces-conf")
(load.d "theme")
(load.d "extras")
(load.d "auto-complete-conf")

(load.d "conf-conf")
(load.d "lisp")
(load.d "rust-conf")
(load.d "c-conf")
(load.d "python-conf")
(load.d "java-conf")
(load.d "scala-conf")
(load.d "erlang-conf")
(load.d "clojure-conf")
(load.d "elixir-conf")
(load.d "web-conf")
(load.d "sql-conf")
(load.d "js-conf")
(load.d "yaml-conf")
(load.d "html-conf")
(load.d "markdown-conf")
(load.d "screen-writing-conf")

(load.d "external/dired+")
